# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: cyounes
google_analytics: cyounes
title: SomeCode.NET Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Younes

description: Personal blog and more...
author:
  name: Younes Cheikh
  email: A16pkl.L3kPN3@qTePE.L1T
  github: cyounes
  twitter: cyounes
  #pinterest: asd123
  linkedin: cyounes
  bio: I am a person who has high passion in programing and development, and have been loving every minute of it... C# .NET addicted :)
  email_md5: aa413781a3cc7b265536282483dbe8a0

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate

ImagesFolder: /Content/Images
