# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: cyounes
google_analytics: cyounes
title: Younes Cheikh

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Younes Cheikh

description: Personal blog and more...
author:
  name: Younes Cheikh
  email: firstname dot cheikh at gmail dot come
  github: cyounes
  twitter: cyounes
  #pinterest: asd123
  linkedin: cyounes
  bio: Just another .NET Developer!
  email_md5: aa413781a3cc7b265536282483dbe8a0

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate

ImagesFolder: /Content/Images