# General Jekyll Config
highlighter: rouge
url: http://cyounes.com
lsi: false
ImagesFolder: /Content/Images
markdown: redcarpet
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

